<?php

namespace Database\Seeders;

use App\Models\Cliente;
use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ClienteSeeder extends Seeder
{
    use WithoutModelEvents;

    public function run(): void
    {
        $vendedores = User::query()
            ->whereIn('email', ['admin@distribuidora.com', 'distribuidorasac@distribuidora.com'])
            ->pluck('id', 'email');

        $vendedorId = $vendedores->get('admin@distribuidora.com') ?? $vendedores->first();

        $clientes = [
            [
                'codigo' => 'CLI-001',
                'tipo_documento' => 'RUC',
                'numero_documento' => '20100123456',
                'razon_social' => 'Comercial San Antonio S.A.C.',
                'nombre_comercial' => 'San Antonio',
                'telefono' => '511987654321',
                'email' => 'ventas@sanantonio.com.pe',
                'direccion' => 'Av. Arenales 1245, Miraflores',
                'departamento' => 'Lima',
                'provincia' => 'Lima',
                'distrito' => 'Miraflores',
                'vendedor_id' => $vendedorId,
                'limite_credito' => 25000.00,
                'dias_credito' => 30,
                'estado' => 'Activo',
                'notas' => 'Cliente de alta rotación, paga puntual.',
            ],
            [
                'codigo' => 'CLI-002',
                'tipo_documento' => 'RUC',
                'numero_documento' => '20512345678',
                'razon_social' => 'Distribuciones El Sol E.I.R.L.',
                'nombre_comercial' => 'El Sol',
                'telefono' => '511912345678',
                'email' => 'compras@delsol.com.pe',
                'direccion' => 'Jr. Cusco 456, Cercado',
                'departamento' => 'Lima',
                'provincia' => 'Lima',
                'distrito' => 'Lima',
                'vendedor_id' => $vendedorId,
                'limite_credito' => 15000.00,
                'dias_credito' => 15,
                'estado' => 'Activo',
                'notas' => null,
            ],
            [
                'codigo' => 'CLI-003',
                'tipo_documento' => 'DNI',
                'numero_documento' => '41234567',
                'razon_social' => 'María Fernanda Torres Vega',
                'nombre_comercial' => null,
                'telefono' => '51976543210',
                'email' => 'mftorres@gmail.com',
                'direccion' => 'Av. Las Américas 789, Surquillo',
                'departamento' => 'Lima',
                'provincia' => 'Lima',
                'distrito' => 'Surquillo',
                'vendedor_id' => null,
                'limite_credito' => 5000.00,
                'dias_credito' => 15,
                'estado' => 'Activo',
                'notas' => 'Compra al contado en su mayoría.',
            ],
            [
                'codigo' => 'CLI-004',
                'tipo_documento' => 'RUC',
                'numero_documento' => '20178945632',
                'razon_social' => 'Inversiones Norte S.A.C.',
                'nombre_comercial' => 'Inversiones Norte',
                'telefono' => '51441234567',
                'email' => 'contacto@invnorte.com.pe',
                'direccion' => 'Av. Fco. Bolognesi 321, Trujillo',
                'departamento' => 'La Libertad',
                'provincia' => 'Trujillo',
                'distrito' => 'Trujillo',
                'vendedor_id' => $vendedorId,
                'limite_credito' => 30000.00,
                'dias_credito' => 45,
                'estado' => 'Activo',
                'notas' => 'Atender con prioridad en campaña navideña.',
            ],
            [
                'codigo' => 'CLI-005',
                'tipo_documento' => 'RUC',
                'numero_documento' => '20198765432',
                'razon_social' => 'Bodegón Central S.A.',
                'nombre_comercial' => 'Bodegón',
                'telefono' => '51987654321',
                'email' => 'pedidos@bodegoncentral.com.pe',
                'direccion' => 'Av. Caquetá 210, San Martín de Porres',
                'departamento' => 'Lima',
                'provincia' => 'Lima',
                'distrito' => 'San Martín de Porres',
                'vendedor_id' => $vendedorId,
                'limite_credito' => 18000.00,
                'dias_credito' => 30,
                'estado' => 'Activo',
                'notas' => null,
            ],
            [
                'codigo' => 'CLI-006',
                'tipo_documento' => 'DNI',
                'numero_documento' => '46578912',
                'razon_social' => 'Jorge Luis Medina Flores',
                'nombre_comercial' => null,
                'telefono' => '51966778899',
                'email' => 'jlmedina@hotmail.com',
                'direccion' => 'Calle Los Álamos 198, Cercado',
                'departamento' => 'Arequipa',
                'provincia' => 'Arequipa',
                'distrito' => 'Arequipa',
                'vendedor_id' => null,
                'limite_credito' => 3500.00,
                'dias_credito' => 15,
                'estado' => 'Activo',
                'notas' => 'Cliente nuevo, primer crédito aprobado.',
            ],
            [
                'codigo' => 'CLI-007',
                'tipo_documento' => 'RUC',
                'numero_documento' => '20543219876',
                'razon_social' => 'Corporación Almacenes del Perú S.A.C.',
                'nombre_comercial' => 'Codape',
                'telefono' => '51871234567',
                'email' => 'compras@codape.com.pe',
                'direccion' => 'Jr. Puno 854, Puno',
                'departamento' => 'Puno',
                'provincia' => 'Puno',
                'distrito' => 'Puno',
                'vendedor_id' => $vendedorId,
                'limite_credito' => 22000.00,
                'dias_credito' => 60,
                'estado' => 'Activo',
                'notas' => 'Opera en zona sur, coordinar despacho con anticipación.',
            ],
            [
                'codigo' => 'CLI-008',
                'tipo_documento' => 'RUC',
                'numero_documento' => '20131415926',
                'razon_social' => 'Mercados Los Andes S.A.C.',
                'nombre_comercial' => 'Los Andes',
                'telefono' => '51944556677',
                'email' => 'gerencia@losandes.com.pe',
                'direccion' => 'Av. Divina Pastora 456, Independencia',
                'departamento' => 'Lima',
                'provincia' => 'Lima',
                'distrito' => 'Independencia',
                'vendedor_id' => $vendedorId,
                'limite_credito' => 12000.00,
                'dias_credito' => 30,
                'estado' => 'Suspendido',
                'notas' => 'Crédito suspendido por factura vencida.',
            ],
            [
                'codigo' => 'CLI-009',
                'tipo_documento' => 'RUC',
                'numero_documento' => '20415987632',
                'razon_social' => 'Abastos del Río S.A.C.',
                'nombre_comercial' => 'Abastos del Río',
                'telefono' => '51933445566',
                'email' => 'ventas@abastosdelrio.com.pe',
                'direccion' => 'Calle Los Nogales 250, San Juan de Lurigancho',
                'departamento' => 'Lima',
                'provincia' => 'Lima',
                'distrito' => 'San Juan de Lurigancho',
                'vendedor_id' => $vendedorId,
                'limite_credito' => 9000.00,
                'dias_credito' => 15,
                'estado' => 'Activo',
                'notas' => null,
            ],
            [
                'codigo' => 'CLI-010',
                'tipo_documento' => 'DNI',
                'numero_documento' => '47890123',
                'razon_social' => 'Rosa Elena Quispe Mamani',
                'nombre_comercial' => null,
                'telefono' => '51922334455',
                'email' => 'rosa.quispe@gmail.com',
                'direccion' => 'Jr. Puno 124, Cusco',
                'departamento' => 'Cusco',
                'provincia' => 'Cusco',
                'distrito' => 'Cusco',
                'vendedor_id' => null,
                'limite_credito' => 4000.00,
                'dias_credito' => 30,
                'estado' => 'Activo',
                'notas' => 'Compra para tienda propia de abarrotes.',
            ],
            [
                'codigo' => 'CLI-011',
                'tipo_documento' => 'RUC',
                'numero_documento' => '20587654321',
                'razon_social' => 'Especialidades Gastronómicas del Sur E.I.R.L.',
                'nombre_comercial' => 'Gastro Sur',
                'telefono' => '51549876581',
                'email' => 'contacto@gastrosur.com.pe',
                'direccion' => 'Av. Víctor Raúl 890, Arequipa',
                'departamento' => 'Arequipa',
                'provincia' => 'Arequipa',
                'distrito' => 'Cayma',
                'vendedor_id' => $vendedorId,
                'limite_credito' => 16000.00,
                'dias_credito' => 30,
                'estado' => 'Activo',
                'notas' => 'Programar entregas solo en horario de mañana.',
            ],
            [
                'codigo' => 'CLI-012',
                'tipo_documento' => 'RUC',
                'numero_documento' => '20612131415',
                'razon_social' => 'Tiendas La Fortuna S.A.C.',
                'nombre_comercial' => 'La Fortuna',
                'telefono' => '51922334477',
                'email' => 'abastecimiento@lafortuna.com.pe',
                'direccion' => 'Av. Separadora Industrial 1200, José Luis Bustamante',
                'departamento' => 'Arequipa',
                'provincia' => 'Arequipa',
                'distrito' => 'José Luis Bustamante',
                'vendedor_id' => $vendedorId,
                'limite_credito' => 20000.00,
                'dias_credito' => 45,
                'estado' => 'Activo',
                'notas' => 'Sucursal en Juliaca en evaluación de crédito.',
            ],
        ];

        foreach ($clientes as $cliente) {
            Cliente::updateOrCreate(
                ['numero_documento' => $cliente['numero_documento']],
                $cliente
            );
        }
    }
}
