<?php

namespace Database\Seeders;

use App\Models\Proveedor;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProveedorSeeder extends Seeder
{
    use WithoutModelEvents;

    public function run(): void
    {
        $proveedores = [
            [
                'codigo' => 'PROV-001',
                'tipo_documento' => 'RUC',
                'numero_documento' => '20100047218',
                'razon_social' => 'Alicorp S.A.A.',
                'nombre_comercial' => 'Alicorp',
                'telefono' => '51744567890',
                'email' => 'creditos@alicorp.com.pe',
                'direccion' => 'Av. Argentina 4793, Bellavista',
                'departamento' => 'Callao',
                'provincia' => 'Callao',
                'distrito' => 'Bellavista',
                'limite_credito' => 80000.00,
                'dias_credito' => 60,
                'estado' => 'Activo',
                'notas' => 'Proveedor principal de abarrotes, línea 1.',
            ],
            [
                'codigo' => 'PROV-002',
                'tipo_documento' => 'RUC',
                'numero_documento' => '20100130827',
                'razon_social' => 'Bimbo del Perú S.A.',
                'nombre_comercial' => 'Bimbo',
                'telefono' => '51120034567',
                'email' => 'ventas@bimbo.com.pe',
                'direccion' => 'Av. Los Frutales 355, Ate',
                'departamento' => 'Lima',
                'provincia' => 'Lima',
                'distrito' => 'Ate',
                'limite_credito' => 45000.00,
                'dias_credito' => 30,
                'estado' => 'Activo',
                'notas' => null,
            ],
            [
                'codigo' => 'PROV-003',
                'tipo_documento' => 'RUC',
                'numero_documento' => '20500901018',
                'razon_social' => 'Gloria S.A.',
                'nombre_comercial' => 'Gloria',
                'telefono' => '51911223344',
                'email' => 'pedidos@gloria.com.pe',
                'direccion' => 'Av. Los Ángeles 208, Lima',
                'departamento' => 'Lima',
                'provincia' => 'Lima',
                'distrito' => 'Independencia',
                'limite_credito' => 50000.00,
                'dias_credito' => 45,
                'estado' => 'Activo',
                'notas' => 'Preferir embarques en container completo.',
            ],
            [
                'codigo' => 'PROV-004',
                'tipo_documento' => 'RUC',
                'numero_documento' => '20100523616',
                'razon_social' => 'Sociedad Minera Refinería de Zinc S.A.',
                'nombre_comercial' => 'Refinez',
                'telefono' => '51873123144',
                'email' => 'comercial@refinez.com.pe',
                'direccion' => 'Av. Los Industriales 14, Cajamarca',
                'departamento' => 'Cajamarca',
                'provincia' => 'Cajamarca',
                'distrito' => 'La Encañada',
                'limite_credito' => 12000.00,
                'dias_credito' => 30,
                'estado' => 'Inactivo',
                'notas' => 'Sin operaciones desde el semestre pasado.',
            ],
            [
                'codigo' => 'PROV-005',
                'tipo_documento' => 'RUC',
                'numero_documento' => '20512050129',
                'razon_social' => 'Comercial Minera San Marcos S.A.C.',
                'nombre_comercial' => 'San Marcos',
                'telefono' => '51987655432',
                'email' => 'ventas@sancos.com.pe',
                'direccion' => 'Av. Universitaria 1201, Lima',
                'departamento' => 'Lima',
                'provincia' => 'Lima',
                'distrito' => 'San Miguel',
                'limite_credito' => 30000.00,
                'dias_credito' => 45,
                'estado' => 'Activo',
                'notas' => null,
            ],
            [
                'codigo' => 'PROV-006',
                'tipo_documento' => 'RUC',
                'numero_documento' => '20112345678',
                'razon_social' => 'Agroindustria La Huaca S.A.C.',
                'nombre_comercial' => 'La Huaca',
                'telefono' => '51665432100',
                'email' => 'contacto@lahuaca.com.pe',
                'direccion' => 'Av. Santa Rosa 456, Chiclayo',
                'departamento' => 'Lambayeque',
                'provincia' => 'Chiclayo',
                'distrito' => 'Chiclayo',
                'limite_credito' => 18000.00,
                'dias_credito' => 60,
                'estado' => 'Activo',
                'notas' => 'Temporal: proveedor fresco de productos agroindustriales.',
            ],
            [
                'codigo' => 'PROV-007',
                'tipo_documento' => 'RUC',
                'numero_documento' => '20315478963',
                'razon_social' => 'Importadora Wiracocha S.A.',
                'nombre_comercial' => 'Wiracocha',
                'telefono' => '51899887766',
                'email' => 'compras@wiracocha.com.pe',
                'direccion' => 'Calle Los Negocios 200, Cusco',
                'departamento' => 'Cusco',
                'provincia' => 'Cusco',
                'distrito' => 'San Sebastián',
                'limite_credito' => 25000.00,
                'dias_credito' => 30,
                'estado' => 'Activo',
                'notas' => null,
            ],
            [
                'codigo' => 'PROV-008',
                'tipo_documento' => 'RUC',
                'numero_documento' => '20574185263',
                'razon_social' => 'Distribuidora Peruana de Lácteos S.A.C.',
                'nombre_comercial' => 'DPL',
                'telefono' => '51771122334',
                'email' => 'ventas@dpl.com.pe',
                'direccion' => 'Av. De la Encalada 351, Surco',
                'departamento' => 'Lima',
                'provincia' => 'Lima',
                'distrito' => 'Surco',
                'limite_credito' => 40000.00,
                'dias_credito' => 45,
                'estado' => 'Activo',
                'notas' => 'Exigencia de ficha técnica con cada lote.',
            ],
            [
                'codigo' => 'PROV-009',
                'tipo_documento' => 'RUC',
                'numero_documento' => '20123456789',
                'razon_social' => 'Ferreterías Cinecito S.A.C.',
                'nombre_comercial' => 'Cinecito',
                'telefono' => '51996385274',
                'email' => 'gerencia@cinecito.com.pe',
                'direccion' => 'Jr. Huánuco 89, Iquitos',
                'departamento' => 'Loreto',
                'provincia' => 'Maynas',
                'distrito' => 'Iquitos',
                'limite_credito' => 10000.00,
                'dias_credito' => 15,
                'estado' => 'Suspendido',
                'notas' => 'Rechazó dos lotes por incumplimiento de calidad.',
            ],
            [
                'codigo' => 'PROV-010',
                'tipo_documento' => 'RUC',
                'numero_documento' => '20611020304',
                'razon_social' => 'Embotelladoras Andinas S.A.C.',
                'nombre_comercial' => 'Andinas',
                'telefono' => '51745671234',
                'email' => 'contacto@andinas.com.pe',
                'direccion' => 'Av. Industria 850, Ate',
                'departamento' => 'Lima',
                'provincia' => 'Lima',
                'distrito' => 'Ate',
                'limite_credito' => 22000.00,
                'dias_credito' => 30,
                'estado' => 'Activo',
                'notas' => 'Nuevo proveedor, periodo de prueba 3 meses.',
            ],
        ];

        foreach ($proveedores as $proveedor) {
            Proveedor::updateOrCreate(
                ['numero_documento' => $proveedor['numero_documento']],
                $proveedor
            );
        }
    }
}
